// PR Explorer Madeira — Webcam-Datensatz
// Stand: Juni 2026 — 20 aktive Streams
window.MADEIRA_WEBCAMS = [
  {
    "id": "cam01",
    "name": "Funchal Marina 1",
    "region": "Funchal",
    "beschreibung": "Hafen, Kreuzfahrtschiffe, Avenida do Mar",
    "lat": 32.6466,
    "lng": -16.9126,
    "youtubeId": "sTAWMDWmRf0",
    "embedUrl": "https://www.youtube-nocookie.com/embed/sTAWMDWmRf0",
    "watchUrl": "https://www.youtube.com/live/sTAWMDWmRf0",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam02",
    "name": "Funchal Marina 2",
    "region": "Funchal",
    "beschreibung": "Weitwinkel Funchal-Bucht, Praça do Povo, Avenida Sá Carneiro",
    "lat": 32.6468,
    "lng": -16.913,
    "youtubeId": "afyrMxe0qjg",
    "embedUrl": "https://www.youtube-nocookie.com/embed/afyrMxe0qjg",
    "watchUrl": "https://www.youtube.com/live/afyrMxe0qjg",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam03",
    "name": "Funchal City – São Roque Panorama",
    "region": "Funchal",
    "beschreibung": "Panorama über die gesamte Funchal-Bucht von den Hügeln São Roques",
    "lat": 32.66,
    "lng": -16.899,
    "youtubeId": "t4x0u0ARLwo",
    "embedUrl": "https://www.youtube-nocookie.com/embed/t4x0u0ARLwo",
    "watchUrl": "https://www.youtube.com/live/t4x0u0ARLwo",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam04",
    "name": "Funchal – Hotel Penha de França Mar",
    "region": "Funchal",
    "beschreibung": "Meerespool, Atlantik-Panorama, Hotel-Küstenbereich",
    "lat": 32.6455,
    "lng": -16.902,
    "youtubeId": "hUavUKN7O4s",
    "embedUrl": "https://www.youtube-nocookie.com/embed/hUavUKN7O4s",
    "watchUrl": "https://www.youtube.com/live/hUavUKN7O4s",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam05",
    "name": "Funchal – Praia Formosa",
    "region": "Funchal West",
    "beschreibung": "Größter Strand Madeiras, Promenade",
    "lat": 32.639,
    "lng": -16.942,
    "youtubeId": "0QUto3lSCh8",
    "embedUrl": "https://www.youtube-nocookie.com/embed/0QUto3lSCh8",
    "watchUrl": "https://youtu.be/0QUto3lSCh8",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam06",
    "name": "Funchal – Lido Bathing Complex",
    "region": "Funchal West",
    "beschreibung": "Beliebter Meerespool-Komplex, Lido-Promenade",
    "lat": 32.644,
    "lng": -16.937,
    "youtubeId": "xOUhPimEMw4",
    "embedUrl": "https://www.youtube-nocookie.com/embed/xOUhPimEMw4",
    "watchUrl": "https://youtu.be/xOUhPimEMw4",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam07",
    "name": "Funchal – Ponta Gorda Beach",
    "region": "Funchal West",
    "beschreibung": "Strandbad-Komplex Ponta Gorda westlich des Lido",
    "lat": 32.6435,
    "lng": -16.935,
    "youtubeId": "8_IvM-qKWvI",
    "embedUrl": "https://www.youtube-nocookie.com/embed/8_IvM-qKWvI",
    "watchUrl": "https://youtu.be/8_IvM-qKWvI",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam08",
    "name": "Funchal – Barreirinha",
    "region": "Funchal Ost",
    "beschreibung": "Naturbad-Komplex östlich der Zona Velha",
    "lat": 32.6442,
    "lng": -16.895,
    "youtubeId": "46L7FMm0MRY",
    "embedUrl": "https://www.youtube-nocookie.com/embed/46L7FMm0MRY",
    "watchUrl": "https://youtu.be/46L7FMm0MRY",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam09",
    "name": "Funchal – Doca do Cavacas",
    "region": "Funchal West",
    "beschreibung": "Felsenpool westlich Funchal, Atlantikblick",
    "lat": 32.6431,
    "lng": -16.9314,
    "youtubeId": "Wwmv233GOvQ",
    "embedUrl": "https://www.youtube-nocookie.com/embed/Wwmv233GOvQ",
    "watchUrl": "https://youtu.be/Wwmv233GOvQ",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam10",
    "name": "Funchal – Sunseterrace / Praia Formosa 2",
    "region": "Funchal West",
    "beschreibung": "Zweite Kamera Praia Formosa / Sunseterrace Bar Centromar",
    "lat": 32.6388,
    "lng": -16.9435,
    "youtubeId": "5hg111TE3xI",
    "embedUrl": "https://www.youtube-nocookie.com/embed/5hg111TE3xI",
    "watchUrl": "https://youtu.be/5hg111TE3xI",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam11",
    "name": "Câmara de Lobos – Miradouro Cruz da Caldeira",
    "region": "Câmara de Lobos",
    "beschreibung": "Panorama über Fischerhafen und Cabo Girão",
    "lat": 32.649,
    "lng": -16.983,
    "youtubeId": "-p1Xnt9n0yg",
    "embedUrl": "https://www.youtube-nocookie.com/embed/-p1Xnt9n0yg",
    "watchUrl": "https://www.youtube.com/live/-p1Xnt9n0yg",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam12",
    "name": "Calheta Beach",
    "region": "Calheta",
    "beschreibung": "Sandstrand Calheta, Atlantik-Panorama, Südwestküste",
    "lat": 32.718,
    "lng": -17.17,
    "youtubeId": "f6D3Zq6J5A8",
    "embedUrl": "https://www.youtube-nocookie.com/embed/f6D3Zq6J5A8",
    "watchUrl": "https://www.youtube.com/live/f6D3Zq6J5A8",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam13",
    "name": "Porto Moniz – Naturpools",
    "region": "Porto Moniz",
    "beschreibung": "Lava-Naturpools, Nordwestspitze Madeiras",
    "lat": 32.868,
    "lng": -17.166,
    "youtubeId": "UfuspS8uXQg",
    "embedUrl": "https://www.youtube-nocookie.com/embed/UfuspS8uXQg",
    "watchUrl": "https://www.youtube.com/live/UfuspS8uXQg",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam14",
    "name": "Paul do Mar",
    "region": "Paul do Mar",
    "beschreibung": "Fischerdorf, Surfer-Spot, Steilküste Westseite",
    "lat": 32.76,
    "lng": -17.22,
    "youtubeId": "mUgnMZQxJFg",
    "embedUrl": "https://www.youtube-nocookie.com/embed/mUgnMZQxJFg",
    "watchUrl": "https://www.youtube.com/live/mUgnMZQxJFg",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam15",
    "name": "Ponta Delgada – Nordküste",
    "region": "Nordküste",
    "beschreibung": "Meerespool und Küstenpanorama Nordküste",
    "lat": 32.825,
    "lng": -17.072,
    "youtubeId": "igioSn9nFwg",
    "embedUrl": "https://www.youtube-nocookie.com/embed/igioSn9nFwg",
    "watchUrl": "https://www.youtube.com/live/igioSn9nFwg",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam16",
    "name": "Porto da Cruz – Alagoa Beach",
    "region": "Porto da Cruz",
    "beschreibung": "Strand und Felsenküste Nordostseite",
    "lat": 32.778,
    "lng": -16.828,
    "youtubeId": "n5z4uxlus8k",
    "embedUrl": "https://www.youtube-nocookie.com/embed/n5z4uxlus8k",
    "watchUrl": "https://www.youtube.com/live/n5z4uxlus8k",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam17",
    "name": "Santana – Quinta do Furão",
    "region": "Santana",
    "beschreibung": "Weingut an der Steilküste Nordostseite",
    "lat": 32.805,
    "lng": -16.89,
    "youtubeId": "Zy12G-fkto0",
    "embedUrl": "https://www.youtube-nocookie.com/embed/Zy12G-fkto0",
    "watchUrl": "https://www.youtube.com/live/Zy12G-fkto0",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam18",
    "name": "Machico – Forum & Hafen",
    "region": "Machico",
    "beschreibung": "Stadtblick Machico, Sandstrand und Hafenbucht",
    "lat": 32.716,
    "lng": -16.768,
    "youtubeId": "Q3-4IwXgHU0",
    "embedUrl": "https://www.youtube-nocookie.com/embed/Q3-4IwXgHU0",
    "watchUrl": "https://www.youtube.com/live/Q3-4IwXgHU0",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam19",
    "name": "Caniçal – Whale Museum",
    "region": "Caniçal / Ostspitze",
    "beschreibung": "Dorfpanorama, Nähe São Lourenço-Halbinsel, Walfangmuseum",
    "lat": 32.736,
    "lng": -16.734,
    "youtubeId": "ofESg868kBk",
    "embedUrl": "https://www.youtube-nocookie.com/embed/ofESg868kBk",
    "watchUrl": "https://www.youtube.com/live/ofESg868kBk",
    "quelle": "madeira-web.com"
  },
  {
    "id": "cam20",
    "name": "Flughafen Madeira – Runway Cam",
    "region": "Santa Cruz",
    "beschreibung": "Planespotting, Landebahn über dem Meer, Crosswind-Landungen",
    "lat": 32.6978,
    "lng": -16.7762,
    "youtubeId": "KUnIxGXKox0",
    "embedUrl": "https://www.youtube-nocookie.com/embed/KUnIxGXKox0",
    "watchUrl": "https://www.youtube.com/live/KUnIxGXKox0",
    "quelle": "madeira-web.com"
  }
];
window.MADEIRA_WEBCAMS.forEach(cam=>{const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent);cam.mapsUrl=isIOS?`maps://maps.apple.com/?ll=${cam.lat},${cam.lng}&q=${encodeURIComponent(cam.name)}`:`https://www.google.com/maps/search/?api=1&query=${cam.lat},${cam.lng}`;});
